name: Raspberry Pi TUI Build
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build TUI for Raspberry Pi
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pguyot/arm-runner-action@v2.6.5
        with:
          base_image: dietpi:rpi_armv8_bullseye
          cpu: cortex-a53
          bind_mount_repository: true
          image_additional_mb: 10240
          optimize_image: false
          commands: |
            # Rust complains (rightly) that $HOME doesn't match eid home
            export HOME=/root
            # Workaround to CI worker being stuck on Updating crates.io index
            export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
            # Install setup prerequisites
            apt-get update -y --allow-releaseinfo-change
            apt-get upgrade -y
            # Install build tools for TUI only
            apt-get install curl build-essential libssl-dev -y
            curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal
            . "$HOME/.cargo/env"
            # Build the TUI application
            cargo build --release --bin hd-tui

      - name: Upload Release Asset
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} ${{ github.workspace }}/target/release/hd-tui
