name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: wasm32-unknown-unknown

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-ci-${{ hashFiles('**/Cargo.lock') }}

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy on homedisplay crate
        run: cargo clippy -p homedisplay --features network -- -D warnings

      - name: Check TUI builds
        run: cargo check --bin hd-tui

      - name: Check homedisplay library  
        run: cargo check -p homedisplay --features network

      - name: Check frontend (WASM target)
        run: cargo check -p frontend --target wasm32-unknown-unknown

      - name: Run tests
        run: cargo test -p homedisplay --features network